# Generated by Django 5.0.3 on 2024-04-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheep',
            name='professional',
        ),
        migrations.AddField(
            model_name='sheep',
            name='address',
            field=models.CharField(default=1, max_length=50, verbose_name='joylashuv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheep',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sheep',
            name='phone',
            field=models.CharField(default=2, max_length=17),
            preserve_default=False,
        ),
    ]
